// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dsl.proto

package def

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryType int32

const (
	QueryType_One    QueryType = 0
	QueryType_ByIds  QueryType = 1
	QueryType_Paging QueryType = 2
)

var QueryType_name = map[int32]string{
	0: "One",
	1: "ByIds",
	2: "Paging",
}

var QueryType_value = map[string]int32{
	"One":    0,
	"ByIds":  1,
	"Paging": 2,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}

func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{0}
}

type PopulationOption struct {
	Related              map[int32]string `protobuf:"bytes,1,rep,name=related,proto3" json:"related,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WithCounts           bool             `protobuf:"varint,2,opt,name=withCounts,proto3" json:"withCounts,omitempty"`
	WithResources        bool             `protobuf:"varint,3,opt,name=withResources,proto3" json:"withResources,omitempty"`
	HasRelationsWith     *E               `protobuf:"bytes,4,opt,name=hasRelationsWith,proto3" json:"hasRelationsWith,omitempty"`
	HasRelationsOf       []string         `protobuf:"bytes,5,rep,name=hasRelationsOf,proto3" json:"hasRelationsOf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PopulationOption) Reset()         { *m = PopulationOption{} }
func (m *PopulationOption) String() string { return proto.CompactTextString(m) }
func (*PopulationOption) ProtoMessage()    {}
func (*PopulationOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{0}
}

func (m *PopulationOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopulationOption.Unmarshal(m, b)
}
func (m *PopulationOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopulationOption.Marshal(b, m, deterministic)
}
func (m *PopulationOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopulationOption.Merge(m, src)
}
func (m *PopulationOption) XXX_Size() int {
	return xxx_messageInfo_PopulationOption.Size(m)
}
func (m *PopulationOption) XXX_DiscardUnknown() {
	xxx_messageInfo_PopulationOption.DiscardUnknown(m)
}

var xxx_messageInfo_PopulationOption proto.InternalMessageInfo

func (m *PopulationOption) GetRelated() map[int32]string {
	if m != nil {
		return m.Related
	}
	return nil
}

func (m *PopulationOption) GetWithCounts() bool {
	if m != nil {
		return m.WithCounts
	}
	return false
}

func (m *PopulationOption) GetWithResources() bool {
	if m != nil {
		return m.WithResources
	}
	return false
}

func (m *PopulationOption) GetHasRelationsWith() *E {
	if m != nil {
		return m.HasRelationsWith
	}
	return nil
}

func (m *PopulationOption) GetHasRelationsOf() []string {
	if m != nil {
		return m.HasRelationsOf
	}
	return nil
}

type EntityQuery struct {
	Qt                   QueryType          `protobuf:"varint,1,opt,name=qt,proto3,enum=def.QueryType" json:"qt,omitempty"`
	Type                 string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string             `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Ids                  []string           `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`
	PopOp                *PopulationOption  `protobuf:"bytes,5,opt,name=popOp,proto3" json:"popOp,omitempty"`
	User                 *EX                `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Action               string             `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	Queries              []*Query           `protobuf:"bytes,8,rep,name=queries,proto3" json:"queries,omitempty"`
	Sorts                map[string]SortDir `protobuf:"bytes,9,rep,name=sorts,proto3" json:"sorts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=def.SortDir"`
	FromID               string             `protobuf:"bytes,10,opt,name=fromID,proto3" json:"fromID,omitempty"`
	WithLimit            int32              `protobuf:"varint,11,opt,name=withLimit,proto3" json:"withLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EntityQuery) Reset()         { *m = EntityQuery{} }
func (m *EntityQuery) String() string { return proto.CompactTextString(m) }
func (*EntityQuery) ProtoMessage()    {}
func (*EntityQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{1}
}

func (m *EntityQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityQuery.Unmarshal(m, b)
}
func (m *EntityQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityQuery.Marshal(b, m, deterministic)
}
func (m *EntityQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityQuery.Merge(m, src)
}
func (m *EntityQuery) XXX_Size() int {
	return xxx_messageInfo_EntityQuery.Size(m)
}
func (m *EntityQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityQuery.DiscardUnknown(m)
}

var xxx_messageInfo_EntityQuery proto.InternalMessageInfo

func (m *EntityQuery) GetQt() QueryType {
	if m != nil {
		return m.Qt
	}
	return QueryType_One
}

func (m *EntityQuery) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EntityQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EntityQuery) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *EntityQuery) GetPopOp() *PopulationOption {
	if m != nil {
		return m.PopOp
	}
	return nil
}

func (m *EntityQuery) GetUser() *EX {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EntityQuery) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *EntityQuery) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *EntityQuery) GetSorts() map[string]SortDir {
	if m != nil {
		return m.Sorts
	}
	return nil
}

func (m *EntityQuery) GetFromID() string {
	if m != nil {
		return m.FromID
	}
	return ""
}

func (m *EntityQuery) GetWithLimit() int32 {
	if m != nil {
		return m.WithLimit
	}
	return 0
}

type EntityCreate struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	E_                   *E       `protobuf:"bytes,2,opt,name=e_,json=e,proto3" json:"e_,omitempty"`
	Related_             []*EX    `protobuf:"bytes,3,rep,name=related_,json=related,proto3" json:"related_,omitempty"`
	Resources_           []*E     `protobuf:"bytes,4,rep,name=resources_,json=resources,proto3" json:"resources_,omitempty"`
	User                 *EX      `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Action               string   `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityCreate) Reset()         { *m = EntityCreate{} }
func (m *EntityCreate) String() string { return proto.CompactTextString(m) }
func (*EntityCreate) ProtoMessage()    {}
func (*EntityCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{2}
}

func (m *EntityCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityCreate.Unmarshal(m, b)
}
func (m *EntityCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityCreate.Marshal(b, m, deterministic)
}
func (m *EntityCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityCreate.Merge(m, src)
}
func (m *EntityCreate) XXX_Size() int {
	return xxx_messageInfo_EntityCreate.Size(m)
}
func (m *EntityCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityCreate.DiscardUnknown(m)
}

var xxx_messageInfo_EntityCreate proto.InternalMessageInfo

func (m *EntityCreate) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EntityCreate) GetE_() *E {
	if m != nil {
		return m.E_
	}
	return nil
}

func (m *EntityCreate) GetRelated_() []*EX {
	if m != nil {
		return m.Related_
	}
	return nil
}

func (m *EntityCreate) GetResources_() []*E {
	if m != nil {
		return m.Resources_
	}
	return nil
}

func (m *EntityCreate) GetUser() *EX {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EntityCreate) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type EntityUpdate struct {
	Type                 string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	OfID                 string    `protobuf:"bytes,2,opt,name=ofID,proto3" json:"ofID,omitempty"`
	Queries              []*Query  `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	Updates              []*Update `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`
	User                 *EX       `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Action               string    `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EntityUpdate) Reset()         { *m = EntityUpdate{} }
func (m *EntityUpdate) String() string { return proto.CompactTextString(m) }
func (*EntityUpdate) ProtoMessage()    {}
func (*EntityUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{3}
}

func (m *EntityUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityUpdate.Unmarshal(m, b)
}
func (m *EntityUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityUpdate.Marshal(b, m, deterministic)
}
func (m *EntityUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityUpdate.Merge(m, src)
}
func (m *EntityUpdate) XXX_Size() int {
	return xxx_messageInfo_EntityUpdate.Size(m)
}
func (m *EntityUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EntityUpdate proto.InternalMessageInfo

func (m *EntityUpdate) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EntityUpdate) GetOfID() string {
	if m != nil {
		return m.OfID
	}
	return ""
}

func (m *EntityUpdate) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *EntityUpdate) GetUpdates() []*Update {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *EntityUpdate) GetUser() *EX {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EntityUpdate) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type RelationQuery struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	OfID                 *EX               `protobuf:"bytes,2,opt,name=ofID,proto3" json:"ofID,omitempty"`
	Relation             string            `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	User                 *EX               `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	PopOp                *PopulationOption `protobuf:"bytes,5,opt,name=popOp,proto3" json:"popOp,omitempty"`
	FromID               string            `protobuf:"bytes,6,opt,name=fromID,proto3" json:"fromID,omitempty"`
	WithLimit            int32             `protobuf:"varint,7,opt,name=withLimit,proto3" json:"withLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RelationQuery) Reset()         { *m = RelationQuery{} }
func (m *RelationQuery) String() string { return proto.CompactTextString(m) }
func (*RelationQuery) ProtoMessage()    {}
func (*RelationQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{4}
}

func (m *RelationQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationQuery.Unmarshal(m, b)
}
func (m *RelationQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationQuery.Marshal(b, m, deterministic)
}
func (m *RelationQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationQuery.Merge(m, src)
}
func (m *RelationQuery) XXX_Size() int {
	return xxx_messageInfo_RelationQuery.Size(m)
}
func (m *RelationQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RelationQuery proto.InternalMessageInfo

func (m *RelationQuery) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RelationQuery) GetOfID() *EX {
	if m != nil {
		return m.OfID
	}
	return nil
}

func (m *RelationQuery) GetRelation() string {
	if m != nil {
		return m.Relation
	}
	return ""
}

func (m *RelationQuery) GetUser() *EX {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RelationQuery) GetPopOp() *PopulationOption {
	if m != nil {
		return m.PopOp
	}
	return nil
}

func (m *RelationQuery) GetFromID() string {
	if m != nil {
		return m.FromID
	}
	return ""
}

func (m *RelationQuery) GetWithLimit() int32 {
	if m != nil {
		return m.WithLimit
	}
	return 0
}

type RelationCreate struct {
	From_                *EX      `protobuf:"bytes,1,opt,name=from_,json=from,proto3" json:"from_,omitempty"`
	To_                  *EX      `protobuf:"bytes,2,opt,name=to_,json=to,proto3" json:"to_,omitempty"`
	Verb_                string   `protobuf:"bytes,3,opt,name=verb_,json=verb,proto3" json:"verb_,omitempty"`
	User                 *EX      `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	IsAdd_               bool     `protobuf:"varint,5,opt,name=isAdd_,json=isAdd,proto3" json:"isAdd_,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationCreate) Reset()         { *m = RelationCreate{} }
func (m *RelationCreate) String() string { return proto.CompactTextString(m) }
func (*RelationCreate) ProtoMessage()    {}
func (*RelationCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{5}
}

func (m *RelationCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationCreate.Unmarshal(m, b)
}
func (m *RelationCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationCreate.Marshal(b, m, deterministic)
}
func (m *RelationCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationCreate.Merge(m, src)
}
func (m *RelationCreate) XXX_Size() int {
	return xxx_messageInfo_RelationCreate.Size(m)
}
func (m *RelationCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationCreate.DiscardUnknown(m)
}

var xxx_messageInfo_RelationCreate proto.InternalMessageInfo

func (m *RelationCreate) GetFrom_() *EX {
	if m != nil {
		return m.From_
	}
	return nil
}

func (m *RelationCreate) GetTo_() *EX {
	if m != nil {
		return m.To_
	}
	return nil
}

func (m *RelationCreate) GetVerb_() string {
	if m != nil {
		return m.Verb_
	}
	return ""
}

func (m *RelationCreate) GetUser() *EX {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RelationCreate) GetIsAdd_() bool {
	if m != nil {
		return m.IsAdd_
	}
	return false
}

func init() {
	proto.RegisterEnum("def.QueryType", QueryType_name, QueryType_value)
	proto.RegisterType((*PopulationOption)(nil), "def.PopulationOption")
	proto.RegisterMapType((map[int32]string)(nil), "def.PopulationOption.RelatedEntry")
	proto.RegisterType((*EntityQuery)(nil), "def.EntityQuery")
	proto.RegisterMapType((map[string]SortDir)(nil), "def.EntityQuery.SortsEntry")
	proto.RegisterType((*EntityCreate)(nil), "def.EntityCreate")
	proto.RegisterType((*EntityUpdate)(nil), "def.EntityUpdate")
	proto.RegisterType((*RelationQuery)(nil), "def.RelationQuery")
	proto.RegisterType((*RelationCreate)(nil), "def.RelationCreate")
}

func init() { proto.RegisterFile("dsl.proto", fileDescriptor_3e64ff22355f731d) }

var fileDescriptor_3e64ff22355f731d = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5f, 0x6b, 0xe3, 0x46,
	0x10, 0xaf, 0x24, 0x4b, 0xb6, 0xc6, 0x8e, 0x71, 0x27, 0x4d, 0x59, 0x9c, 0x10, 0x8c, 0x49, 0x5a,
	0x93, 0x80, 0x21, 0xee, 0x4b, 0x09, 0x7d, 0x69, 0x63, 0x17, 0x02, 0x01, 0xa7, 0x4a, 0x4b, 0xfb,
	0x66, 0x94, 0x68, 0x9d, 0x88, 0x3a, 0x92, 0x2c, 0xad, 0x52, 0xf4, 0x31, 0xfa, 0x7e, 0x9f, 0xe1,
	0x9e, 0xee, 0xe1, 0xee, 0xbb, 0xdc, 0x87, 0x39, 0x76, 0x56, 0xff, 0xe2, 0x73, 0x02, 0x77, 0x2f,
	0x66, 0x67, 0xf6, 0x37, 0x33, 0xbf, 0x99, 0xf9, 0xad, 0x0c, 0xb6, 0x97, 0xac, 0xc6, 0x51, 0x1c,
	0x8a, 0x10, 0x0d, 0x8f, 0x2f, 0xfb, 0xb6, 0xc7, 0x97, 0xca, 0x1e, 0xbe, 0xd5, 0xa1, 0x77, 0x1d,
	0x46, 0xe9, 0xca, 0x15, 0x7e, 0x18, 0xcc, 0x23, 0xf9, 0x8b, 0xbf, 0x40, 0x33, 0xe6, 0x2b, 0x57,
	0x70, 0x8f, 0x69, 0x03, 0x63, 0xd4, 0x9e, 0x0c, 0xc7, 0x32, 0x62, 0x13, 0x37, 0x76, 0x14, 0x68,
	0x16, 0x88, 0x38, 0x73, 0x8a, 0x10, 0x3c, 0x04, 0xf8, 0xcf, 0x17, 0x0f, 0x17, 0x61, 0x1a, 0x88,
	0x84, 0xe9, 0x03, 0x6d, 0xd4, 0x72, 0x6a, 0x1e, 0x3c, 0x82, 0x1d, 0x69, 0x39, 0x3c, 0x09, 0xd3,
	0xf8, 0x8e, 0x27, 0xcc, 0x20, 0xc8, 0x73, 0x27, 0x4e, 0xa0, 0xf7, 0xe0, 0x26, 0x54, 0xc1, 0x0f,
	0x83, 0xe4, 0x6f, 0x5f, 0x3c, 0xb0, 0xc6, 0x40, 0x1b, 0xb5, 0x27, 0x16, 0x91, 0x99, 0x39, 0x9f,
	0xdd, 0xe3, 0x0f, 0xd0, 0xad, 0xfb, 0xe6, 0x4b, 0x66, 0x0e, 0x8c, 0x91, 0xed, 0x6c, 0x78, 0xfb,
	0xe7, 0xd0, 0xa9, 0x53, 0xc7, 0x1e, 0x18, 0xff, 0xf2, 0x8c, 0x69, 0x03, 0x6d, 0x64, 0x3a, 0xf2,
	0x88, 0xdf, 0x81, 0xf9, 0xe4, 0xae, 0x52, 0x4e, 0xf4, 0x6d, 0x47, 0x19, 0xe7, 0xfa, 0xcf, 0xda,
	0xf0, 0x8d, 0x01, 0xed, 0x59, 0x20, 0x7c, 0x91, 0xfd, 0x91, 0xf2, 0x38, 0xc3, 0x43, 0xd0, 0xd7,
	0x82, 0x42, 0xbb, 0x93, 0x2e, 0x31, 0x23, 0xff, 0x9f, 0x59, 0xc4, 0x1d, 0x7d, 0x2d, 0x10, 0xa1,
	0x21, 0xb2, 0xa8, 0x48, 0x44, 0x67, 0xec, 0x82, 0xee, 0x7b, 0xd4, 0xb6, 0xed, 0xe8, 0xbe, 0x27,
	0xeb, 0xfb, 0x5e, 0xc2, 0x1a, 0x44, 0x56, 0x1e, 0xf1, 0x14, 0xcc, 0x28, 0x8c, 0xe6, 0x11, 0x33,
	0xa9, 0xe5, 0xbd, 0xad, 0xf3, 0x77, 0x14, 0x06, 0xf7, 0xa1, 0x91, 0x26, 0x3c, 0x66, 0x16, 0x61,
	0x9b, 0x6a, 0x3c, 0xff, 0x38, 0xe4, 0xc4, 0xef, 0xc1, 0x72, 0xef, 0x24, 0x9a, 0x35, 0xa9, 0x5e,
	0x6e, 0xe1, 0x11, 0x34, 0xd7, 0x29, 0x8f, 0x7d, 0x9e, 0xb0, 0x16, 0xed, 0x18, 0x2a, 0xf2, 0x4e,
	0x71, 0x85, 0x67, 0x60, 0x26, 0x61, 0x2c, 0x12, 0x66, 0x13, 0x66, 0x5f, 0xe5, 0xae, 0xda, 0x1f,
	0xdf, 0xc8, 0x5b, 0x25, 0x00, 0x85, 0x94, 0x05, 0x97, 0x71, 0xf8, 0x78, 0x39, 0x65, 0xa0, 0x0a,
	0x2a, 0x0b, 0x0f, 0xc0, 0x96, 0x1b, 0xbe, 0xf2, 0x1f, 0x7d, 0xc1, 0xda, 0x34, 0xea, 0xca, 0xd1,
	0xff, 0x1d, 0xa0, 0x4a, 0x55, 0x5f, 0x88, 0xad, 0x16, 0x32, 0xac, 0x2f, 0xa4, 0x3b, 0xe9, 0x10,
	0x11, 0x19, 0x31, 0xf5, 0xe3, 0xfa, 0x7a, 0x3e, 0x68, 0xd0, 0x51, 0xfc, 0x2e, 0x62, 0xee, 0x0a,
	0x5e, 0xce, 0x5f, 0xab, 0xcd, 0x7f, 0x0f, 0x74, 0xbe, 0xa0, 0x4c, 0x95, 0x9a, 0x34, 0x8e, 0x43,
	0x68, 0xe5, 0x1a, 0x5e, 0x30, 0x83, 0xfa, 0x2d, 0x67, 0x59, 0x8a, 0xfb, 0x18, 0x20, 0x2e, 0x34,
	0xba, 0xa0, 0x8d, 0x55, 0x29, 0xec, 0xf2, 0xa6, 0x5c, 0x89, 0xf9, 0xfa, 0x4a, 0xac, 0xfa, 0x4a,
	0x86, 0xef, 0x4b, 0xee, 0x7f, 0x45, 0xde, 0x4b, 0xdc, 0x11, 0x1a, 0xe1, 0xf2, 0x72, 0x5a, 0xe8,
	0x49, 0x9e, 0xeb, 0xbb, 0x34, 0x5e, 0xde, 0xe5, 0x31, 0x34, 0x53, 0xca, 0x9b, 0xe4, 0xbc, 0xdb,
	0x84, 0x52, 0xb5, 0x9c, 0xe2, 0xee, 0xeb, 0xa8, 0x7f, 0xd4, 0x60, 0xa7, 0x78, 0x61, 0xea, 0x5d,
	0x6c, 0xe3, 0xbe, 0x5f, 0xe3, 0x5e, 0x4f, 0x4d, 0x4d, 0xf4, 0xf3, 0xe9, 0xcb, 0xe4, 0xea, 0x69,
	0x94, 0x76, 0xc9, 0xa9, 0xb1, 0x8d, 0xd3, 0x17, 0xbd, 0x95, 0x4a, 0x9d, 0xd6, 0xcb, 0xea, 0x6c,
	0x6e, 0xa8, 0x73, 0xf8, 0xbf, 0x06, 0xdd, 0xa2, 0xbd, 0x5c, 0x57, 0x07, 0x60, 0xca, 0xd0, 0x05,
	0x35, 0x58, 0xe7, 0x24, 0xbd, 0xc8, 0xc0, 0x10, 0xe1, 0x62, 0xb3, 0x51, 0x5d, 0x84, 0xb8, 0x0b,
	0xe6, 0x13, 0x8f, 0x6f, 0x17, 0x79, 0x8f, 0x0d, 0x69, 0xbc, 0xde, 0xdf, 0x1e, 0x58, 0x7e, 0xf2,
	0xab, 0xe7, 0x2d, 0xa8, 0xc1, 0x96, 0x63, 0x92, 0x75, 0x72, 0x0a, 0x76, 0xf9, 0xa5, 0xc1, 0x26,
	0x18, 0xf3, 0x80, 0xf7, 0xbe, 0x41, 0x1b, 0xcc, 0xdf, 0xb2, 0x4b, 0x2f, 0xe9, 0x69, 0x08, 0x60,
	0x5d, 0xbb, 0xf7, 0x7e, 0x70, 0xdf, 0xd3, 0x27, 0xef, 0x74, 0x30, 0xa6, 0x37, 0x57, 0x38, 0x00,
	0x23, 0x0c, 0x38, 0xf6, 0x36, 0xdf, 0x71, 0xbf, 0xa8, 0x89, 0x47, 0xf4, 0x2d, 0xda, 0x82, 0x68,
	0xe7, 0x88, 0x2b, 0x3f, 0x11, 0xf8, 0x23, 0x98, 0x91, 0x7b, 0xcf, 0xbd, 0x2d, 0xb8, 0x4e, 0x8e,
	0xbb, 0xa6, 0xfb, 0x13, 0xe8, 0xdc, 0xd1, 0xc0, 0x14, 0x04, 0xbf, 0xad, 0xe1, 0xd5, 0x24, 0xab,
	0xd2, 0x27, 0xd0, 0x51, 0x22, 0xdc, 0x82, 0x55, 0x2a, 0xad, 0xb0, 0x67, 0xb0, 0xb3, 0x26, 0x79,
	0x17, 0x12, 0x41, 0xba, 0x79, 0xa6, 0xc1, 0x0d, 0x2a, 0x67, 0xd0, 0x55, 0x54, 0xca, 0x98, 0xdd,
	0x67, 0x31, 0x39, 0x1d, 0xf5, 0x76, 0x66, 0x8f, 0x91, 0xc8, 0x6e, 0x2d, 0xfa, 0x93, 0xfc, 0xe9,
	0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xc9, 0xff, 0x84, 0x41, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DSLClient is the client API for DSL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSLClient interface {
	One(ctx context.Context, in *EntityQuery, opts ...grpc.CallOption) (*EX, error)
	Ids(ctx context.Context, in *EntityQuery, opts ...grpc.CallOption) (*EXList, error)
	Paged(ctx context.Context, in *EntityQuery, opts ...grpc.CallOption) (*EXPaged, error)
	CreateEntity(ctx context.Context, in *EntityCreate, opts ...grpc.CallOption) (*EX, error)
	UpdateEntity(ctx context.Context, in *EntityUpdate, opts ...grpc.CallOption) (*EX, error)
	QueryRelation(ctx context.Context, in *RelationQuery, opts ...grpc.CallOption) (*EXPaged, error)
	CreateRelation(ctx context.Context, in *RelationCreate, opts ...grpc.CallOption) (*Empty, error)
}

type dSLClient struct {
	cc *grpc.ClientConn
}

func NewDSLClient(cc *grpc.ClientConn) DSLClient {
	return &dSLClient{cc}
}

func (c *dSLClient) One(ctx context.Context, in *EntityQuery, opts ...grpc.CallOption) (*EX, error) {
	out := new(EX)
	err := c.cc.Invoke(ctx, "/def.DSL/one", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSLClient) Ids(ctx context.Context, in *EntityQuery, opts ...grpc.CallOption) (*EXList, error) {
	out := new(EXList)
	err := c.cc.Invoke(ctx, "/def.DSL/ids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSLClient) Paged(ctx context.Context, in *EntityQuery, opts ...grpc.CallOption) (*EXPaged, error) {
	out := new(EXPaged)
	err := c.cc.Invoke(ctx, "/def.DSL/paged", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSLClient) CreateEntity(ctx context.Context, in *EntityCreate, opts ...grpc.CallOption) (*EX, error) {
	out := new(EX)
	err := c.cc.Invoke(ctx, "/def.DSL/createEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSLClient) UpdateEntity(ctx context.Context, in *EntityUpdate, opts ...grpc.CallOption) (*EX, error) {
	out := new(EX)
	err := c.cc.Invoke(ctx, "/def.DSL/updateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSLClient) QueryRelation(ctx context.Context, in *RelationQuery, opts ...grpc.CallOption) (*EXPaged, error) {
	out := new(EXPaged)
	err := c.cc.Invoke(ctx, "/def.DSL/queryRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSLClient) CreateRelation(ctx context.Context, in *RelationCreate, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/def.DSL/createRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSLServer is the server API for DSL service.
type DSLServer interface {
	One(context.Context, *EntityQuery) (*EX, error)
	Ids(context.Context, *EntityQuery) (*EXList, error)
	Paged(context.Context, *EntityQuery) (*EXPaged, error)
	CreateEntity(context.Context, *EntityCreate) (*EX, error)
	UpdateEntity(context.Context, *EntityUpdate) (*EX, error)
	QueryRelation(context.Context, *RelationQuery) (*EXPaged, error)
	CreateRelation(context.Context, *RelationCreate) (*Empty, error)
}

// UnimplementedDSLServer can be embedded to have forward compatible implementations.
type UnimplementedDSLServer struct {
}

func (*UnimplementedDSLServer) One(ctx context.Context, req *EntityQuery) (*EX, error) {
	return nil, status.Errorf(codes.Unimplemented, "method One not implemented")
}
func (*UnimplementedDSLServer) Ids(ctx context.Context, req *EntityQuery) (*EXList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ids not implemented")
}
func (*UnimplementedDSLServer) Paged(ctx context.Context, req *EntityQuery) (*EXPaged, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paged not implemented")
}
func (*UnimplementedDSLServer) CreateEntity(ctx context.Context, req *EntityCreate) (*EX, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (*UnimplementedDSLServer) UpdateEntity(ctx context.Context, req *EntityUpdate) (*EX, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntity not implemented")
}
func (*UnimplementedDSLServer) QueryRelation(ctx context.Context, req *RelationQuery) (*EXPaged, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRelation not implemented")
}
func (*UnimplementedDSLServer) CreateRelation(ctx context.Context, req *RelationCreate) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRelation not implemented")
}

func RegisterDSLServer(s *grpc.Server, srv DSLServer) {
	s.RegisterService(&_DSL_serviceDesc, srv)
}

func _DSL_One_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).One(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/One",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).One(ctx, req.(*EntityQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSL_Ids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).Ids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/Ids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).Ids(ctx, req.(*EntityQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSL_Paged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).Paged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/Paged",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).Paged(ctx, req.(*EntityQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSL_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).CreateEntity(ctx, req.(*EntityCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSL_UpdateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).UpdateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/UpdateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).UpdateEntity(ctx, req.(*EntityUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSL_QueryRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).QueryRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/QueryRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).QueryRelation(ctx, req.(*RelationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSL_CreateRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSLServer).CreateRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/def.DSL/CreateRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSLServer).CreateRelation(ctx, req.(*RelationCreate))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "def.DSL",
	HandlerType: (*DSLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "one",
			Handler:    _DSL_One_Handler,
		},
		{
			MethodName: "ids",
			Handler:    _DSL_Ids_Handler,
		},
		{
			MethodName: "paged",
			Handler:    _DSL_Paged_Handler,
		},
		{
			MethodName: "createEntity",
			Handler:    _DSL_CreateEntity_Handler,
		},
		{
			MethodName: "updateEntity",
			Handler:    _DSL_UpdateEntity_Handler,
		},
		{
			MethodName: "queryRelation",
			Handler:    _DSL_QueryRelation_Handler,
		},
		{
			MethodName: "createRelation",
			Handler:    _DSL_CreateRelation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsl.proto",
}
